### ISSUE TITLE
Openscrapers season/show pack support.

### ISSUE THREAD

**Issue by Tikipeter** [host505/plugin.video.theoath#11]
Hi host505.

Let me know if you need any advice on implementing the recent addition of show packs in openscrapers.

I'd be happy to help if I can.

**Comment by host505** [comment]
Hi Tikipeter, thank you for your consideration, I'll see what it takes to implement it as soon as I have the time (too busy with real life this time of year) and I'll let you know if I have trouble with it.
Thanks again.
