### ISSUE TITLE
4K links not populating

### ISSUE THREAD

**Issue by ShibajiCh** [host505/plugin.video.theoath#13]
Hi @host505,
I noticed that 4K links are not populating properly in The Oath addon, i.e. compared to other addons like Seren, Fen and Venom the no. of 4K links are sometimes Nil or very less in The Oath addon. Could you please check and advise?

**Comment by host505** [comment]
Specific examples and sources filters settings, please.
But keep in mind that I don't have the amount of scrapers most other add-ons have, I only have a few that I consider fast and stable, so don't expect same number of results with other add-ons. I always make sure that if a release is out, it is fetched though. No need to fetch it from a hundred different scrapers.

**Comment by ShibajiCh** [comment]
Hi @host505,
I'm using Nvidia shield tv pro/Windows 10 PC with Kodi 18.9 and The Oath latest version. I'm also having a Real Debrid subscription. An example where I didn't find any 4K links on The Oath is Game of Thrones Season 4 Episode 1. I have many 4K torrents for this Season cached on my Real Debrid account as well. I found several 4K links on Seren, Venom and Fen but on The Oath there was not even a single 4K link for this episode. Please advise.

**Comment by host505** [comment]
Yea it's gonna lack for tvshows as theoath doesn't scrape season/show packs yet.
> Please advise

I guess keep using those other add-ons?

**Comment by ShibajiCh** [comment]
Hi @host505,
OK fine. Thanks a lot for the update! Keep up the good work! I'm closing this issue ticket.
