### ISSUE TITLE
[Feature Request] Possibility of adding Fenom Scrapper

### ISSUE THREAD

**Issue by daking1512** [host505/plugin.video.theoath#15]
Is it possible to add Fenom Scrapper as part of the scrappers the Oath works with? Fenom scrapper has GDrive scrapping implemented which comes in handy for streaming content directly from google drive

Thanks

**Comment by host505** [comment]
I'm afraid not, even if I wanted to I don't think this scraper pack is compatible with theoath.
I'll see in the future if I can make a gdrive scraper, but for now more important things are to be addressed.
Thanks
