### ISSUE TITLE
[oathscrapers] Sources request

### ISSUE THREAD

**Issue by m0rpheas** [host505/plugin.video.theoath#17]
Hey man, good job on the add-on.

Could I request the addition of ymovies.se for movies and yseries.tv for TV shows? They offer many many sources, including HD ones.

I think they are behind cloudflare, but you seem to have cfscrape in place. 

Thanks in advance.

**Comment by host505** [comment]
Nope, the supplied cf solver (or any other free/os cf solver that I know off) cannot solve this type of protection.
Thanks
