### ISSUE TITLE
Is it possible to get clear logos and clear art

### ISSUE THREAD

**Issue by xyzfre** [host505/plugin.video.theoath#18]
Just wanna start off by saying thank you for this amazing add-on and all your hard work ,,was wondering if it's possible to have a feature to enable clear logos and clear art￼ ,,I use AuraMod  
And clear logos looks amazing with the skin￼￼

**Comment by host505** [comment]
Thanks.
There is an option on settings' general tab, 'Enable extra/hq artwork' which if you enable you'll get these types of artwork as well.
Currently it only works for movies and shows, but not on season and episode level.
