### ISSUE TITLE
Use of Openscrapers

### ISSUE THREAD

**Issue by millsmcewan** [host505/plugin.video.theoath#19]
Hello
Thank you for your work on The Oath.  My issue is that I can't get openscrapers to work with The Oath.  I downloaded and installed the Openscrapers repo in order to install the Openscrapers add-on to use with The Oath.  When in Kodi I try to "install from repo" however, it looks like the Openscrapers repo does not have a program add-ons folder.  Am I doing something wrong? Thanks

**Comment by host505** [comment]
Openscrapers can't be used with theoath anymore, as they aren't compatible with kodi 19 (and no idea if they ever will), that's why you can't install it (I assume you use kodi 19).
I removed support for openscrapers as it was causing installation problems for theoath because of this.

**Comment by millsmcewan** [comment]
Thank you for your prompt reply.


Alastair
