### ISSUE TITLE
Dutch translation

### ISSUE THREAD

**Issue by nazegnl** [host505/plugin.video.theoath#2]
@host505 Maybe I'm missing something but the translations are not showing up.

**Comment by host505** [comment]
Do you have kodi's gui language set to English?
It's just the way Exodus & forks work: if you have both add-on's setting and kodi's gui language set on the same language, then both add-on's menu and metadata appear on that language.
If you have the add'on's setting set on a different language than kodi's, then add-on's menu appears on kodi's language and metadata on add-on's setting language.
Here's a s/s with kodi's and add-on's language set to Dutch:
![screenshot000](https://user-images.githubusercontent.com/10226596/57199915-76759500-6f8d-11e9-949c-806d5944f425.png)

**Comment by nazegnl** [comment]
Hmm thought I have them both on Dutch will check ! Thanks
