### ISSUE TITLE
100 movies per page

### ISSUE THREAD

**Issue by adamosborne83** [host505/plugin.video.theoath#22]
Hey,

Not an issue as such.

Just wondering if you could change the page maximum from 400 to say 100?

Next page every 40 programs kills me, especially on a flicking kinda night.

Thank you

**Comment by host505** [comment]
No.
That's too much API calls to the sites that provide us the metadata for free.
That being said, personal trakt & imdb lists aren't paginated, or paginated by 100, so you can use them (till I figure out a way to properly paginate them as well).

**Comment by adamosborne83** [comment]
Sorry, just a little help.

So when I like a list on Trakt, which says has 300 movies or more, would that mean it will show in one page? 

Also, with Seren does that mean he is using more api to get theirs to populate more

**Comment by host505** [comment]
Yes, personal trakt lists aren't paginated.
Not sure about seren, I know it has some initial trakt caching feature when you first run it, but not sure what it caches and what not.

**Comment by adamosborne83** [comment]
As always, thank you for your prompt replies.

Hopefully at some point you can make your main lists to show 100, as I like the genre selection and it seems limitless.
