### ISSUE TITLE
Minor preverence issue

### ISSUE THREAD

**Issue by G-streamer** [host505/plugin.video.theoath#23]
I like to have TheOath display both RD and Free sources as I have a few older TV shows I like to watch, and sometimes the Free links are my hail mary last resort. I have the RD priority in ResolveURL set to 90 but the provider list shows SD RD links below the 720p Free links. Is there any way to get all the free links regardless of resolution, to all display at the bottom of the list? I don't want scraping to progress down an RD list of providers and stop on a free link, when a more stable lower resolution RD link is still available. I have to do a complete re-scrape just to skip over those high resolution free links. Sorry for being petty. lol

**Comment by host505** [comment]
Resolveurl's priority setting has nothing to do with add-on's resolution sorting, it just sorts resolvers based on their priority _after_ the add-on's sorting -- for our case within the same resolution/debrid/non-debrid tag.

I'll think about adding a debrid/non-debrid/res sort option, but no promises, as I've massively re-written the sort/filter functions to behave as they do (filter on a per scraper basis for more accurate pre-emptive results, speed etc -- filtering and sorting are very related internally in the add-on's code), and it was a pita and very fragile.

**Comment by G-streamer** [comment]
Thanks for the reply. I know the amount of work you put into it. It's GREATLY appreciated and highly respected. I just thought I'd toss that out there as a consideration. Wouldn't want you to have nothing more to do. lol

**Comment by host505** [comment]
Ah don't worry about that, there's lots I have/want to do. Wish I knew how though lol.
This is my main learning train, I learn as I go.
Thanks, I appreciate it.

**Comment by host505** [comment]
Well, turned out it wasn't that hard to implement, and I kina liked the idea, so I added it on new ver. 4.00.17.
It's optional, setting under Sources Filters category.

**Comment by G-streamer** [comment]
Holy crap that's awesome. Thank you! I may have to think of something else to challenge you with. LOL

**Comment by host505** [comment]
Added in 409ab1562e766d0535f2c46d005ec378ba7dd9bb
