### ISSUE TITLE
The Oath trakt.tv : Progress Section

### ISSUE THREAD

**Issue by ronfrankhill** [host505/plugin.video.theoath#26]
This is what I observe so far in the trakt.tv progress section of the add-on. I had watched only two episodes of the TV series of the latest 'The Mosquito Coast' but in the Progress Section of trakt.tv it keep saying that I had watched the entire season of it and l only have the final episode to watch. I went to the TV section to do a search of the same TV series 'The Mosquito Coast'. Behold it indicated the correct information which is that l only watched the first 2 episodes of it so maybe trakt progress section of the Oath add-on have an issue in pulling information from trakt.tv site progress section. 
I even cleared the cache in the add-on to make sure but that didn't work concerning the trakt.tv progress section of the add-on.

**Comment by host505** [comment]
I watched the exact same show over the past week, through the My TV shows/Progress section of the add-on, and it worked correctly for all the episodes.
What you described is the expected behaviour of the My TV shows/Episodes list - it will show you the last episode aired. Are you sure you aren't using that one?

**Comment by ronfrankhill** [comment]
It was in the My TV Shows/Progress Section.

**Comment by jewbmx** [comment]
I have ran into the same kinda issues many times with the vast amount of shows i watch and it usually seems to be a glitch with trakt and our addons syncing or caching. Cant recall my usual fixes ive done for it but i do remember that if ya just right click or "long press" the show and view the seasons you can get the proper list and progress with a bit more ease. The problem should resolve itself either from the next addon update process or on its own when a future episodes released.

**Comment by host505** [comment]
Yea probably just cached bad date from trakt.
Nice to see you're still around @jewbmx
