### ISSUE TITLE
The Oath had an update

### ISSUE THREAD

**Issue by eeden003** [host505/plugin.video.theoath#27]
Hi there ! This morning The Oath had an update and now 99% of the 40-50 links are from TELEPISODES and work.
Yesterday only 1 or 2 links for each series that I wanted to watch.
However, a few other streaming sites(íf present)is preferable I think ?
Since the site watchepisodeseries went off line, several addons can only find 1 or 2 working links !
Thanks for your update en keep up the good work !

**Comment by host505** [comment]
No kidding lol
Only we4 went down really. There are at least 4-5 other working scrapers which return free links. If they don't work for you, you might be geoblocked or something.
