### ISSUE TITLE
Orion integration does not seem to be working

### ISSUE THREAD

**Issue by htv4290** [host505/plugin.video.theoath#31]
Hi,

Thanks for this plugin.

I don't seem to be getting any links from Orion.
Not sure if you have been made aware of the issue.

**Setup**

- Installed Orion (4.5.3)
- Authorised (using API key)
- Enabled Orion in Providers
- Stream Type: All
- Other settings left as default

When I search link for a tv episode, there are no links from Orion.

----

Also updated Orion via Orion repo - 4.5.7 - Not working either

**Comment by eeden003** [comment]
Hi there. Well.....The Orion ánd The integration with several add-ons on several Boxes works great here ! Have you checked the status of your account on the Orion site ? Please do, and reactivate your free or paid membership. Also check the status of your Orion account within the addons ánd within Orion itself, is has to be with the status -verified- . Are the Popups in Kodi working when you are using addons ? Orion also has a pop-up in the right-upper-screen when your daily links are all used. Succes.

**Comment by host505** [comment]
Works fine here - have you set Providers/Provider Source at "Oathscrapers + Built-in" or "Built-in" (if you only want Orion)?

**Comment by ebhsgit** [comment]
Thanks for reply guys.

It is working now.

I didn't set Provider to "Oathscrapers + Built-in"

I thought just Enabling Orion was sufficient.
