### ISSUE TITLE
Can't access some Trakt TV Collection shows, after last update. 4.01.04

### ISSUE THREAD

**Issue by gittest598** [host505/plugin.video.theoath#32]
Thank you for your work on The Oath, but the last update 4.01.04 broke access to a SMALL number of Trakt TV Collection shows. Some of which are, Young Shelldon, Roseanne, Alaska The Last Frontier, Wheeler Dealers, all my other approximately 100 shows are fine, when I click on them they open and list the seasons, the ones listed above don't open. I have tried Clearing All Cache, clean Settings file, restarted Kodi and Reauthorized Trakt. Im on a Windows PC running Portable versions of Kodi and I have rolled back to a previous version of The Oath which fixed it, then updated and repeated this problem several times on Kodi 18.9 and 19.1: Looking at the changelog.txt there have been some Trakt fixes, but why would this only affect about 5% of the shows on ny Trakt TV collection? The errors TXT file I have posted happened after the update.
[Kodi Error log.txt](https://github.com/host505/plugin.video.theoath/files/7152501/Kodi.Error.log.txt)

**Comment by host505** [comment]
Yea stupid mistake on last update. Should be fixed now.
Thanks

**Comment by gittest598** [comment]
Thank you for the fast fix, it took me longer to wright about the error than you to fix it. LOL. Tested it on 18.9 and 19.1 both work. Cheers.
