### ISSUE TITLE
Personal OMDB api key

### ISSUE THREAD

**Issue by naudski** [host505/plugin.video.theoath#33]
Hi there!
Could you create this option in your addon?
I get a lot of time-outs. Is that because everyone using this addon is using the same key?
Love your addon by the way!

**Comment by host505** [comment]
I don't use the OMDb api. Where exactly do you get timeouts? Haven't encountered any myself.
I'm gonna need to see your log. Theoath.log, not kodi.log.
Go to add-on's settings, enable debugging, reproduce the problem, then go to Tools/Log functions/Upload log and paste here the link you'll be given.

**Comment by naudski** [comment]
I think the Cosmic Skin is using the OMDB api. Sorry to have bothered you. I will close the issue.

**Comment by jewbmx** [comment]
OMDb has a daily limit of 1000 per api key so you need to make a personal one or code a little ghetto random choice list with a couple in it if possible lol but they gotta be made in a legit fashion so they dont get removed as "bots"
Heres the site page if ya need it or more info.
https://www.omdbapi.com/apikey.aspx
