### ISSUE TITLE
TheOath on SPMC 16.7

### ISSUE THREAD

**Issue by Arfgul** [host505/plugin.video.theoath#34]
After version 4.01.06, TheOath no longer works.  It does not pull any information.  You are only presented with next page.  The only fix is to downgrade to 4.01.06.  It is as if it no longer communicates with IMDB

**Comment by host505** [comment]
I'm surprised it did work until then on such an old kodi version.
Anyway I think I know what broke it on it. I'll send you a test version with a fix to check, I'm not gonna install kodi 16 to check myself.
Ps iirc there has been an spmc 17.x beta version released back then.

**Comment by Arfgul** [comment]
I would appreciate that.  I’ll check it out.  Thank you

**Comment by host505** [comment]
Ok try this https://github.com/host505/random/blob/main/plugin.video.theoath-4.02.02a.zip

**Comment by Arfgul** [comment]
Thank you.  This fixed the New Movies section and the search for movies. New Episodes section is not functional and search for TV shows works for the most part, but sometimes takes a few tries. Everything else works like normal

**Comment by host505** [comment]
I have an old device which had spmc installed, so I checked.
Everything works with the test version above, except stuff coming from tvmaze (new episodes, TV calendar). But that has nothing to do with spmc, it doesn't even work on Kodi 19.
It appears tvmaze's SSL certificate has expired.

**Comment by Arfgul** [comment]
You’re right.  Everything looks good.

**Comment by host505** [comment]
Should be fixed with 941f99819e8749e1ccd1c47664f635db6836f820
