### ISSUE TITLE
Providers

### ISSUE THREAD

**Issue by deeppzy** [host505/plugin.video.theoath#35]
The last time I used TheOath was last friday. I watched Squid Game and it gave me atleast 6+ providers to watch. But when I try to continue my watching today, it only gives me 1 provider and I cant watch it with the only provider given (didnt load). I also tried to watch other show but the result is the same, only get 1 provider.

**Comment by host505** [comment]
I did a small providers update, but I was getting a lot more (free) sources on the show you mentioned even before the update.
You might be geoblocked or isp blocked on some of the providers or something.

**Comment by host505** [comment]
A little more details maybe??? Like kodi version...
Getting only Direct links makes me think resolveurl isn't working on your system.

![screenshot00000](https://user-images.githubusercontent.com/10226596/136396512-13dd90ae-aa37-42a7-b222-1e2ddcb1ec02.png)

![screenshot00001](https://user-images.githubusercontent.com/10226596/136396618-23b8896f-f050-49d5-a870-a456488340cb.png)

**Comment by deeppzy** [comment]
![20211008_193024](https://user-images.githubusercontent.com/91855074/136549562-01a67b74-5b74-44a8-bd58-320537ecd673.jpg)
![20211008_193144](https://user-images.githubusercontent.com/91855074/136549571-1ee3cf3c-d8b9-426f-b37e-67f69762254c.jpg)

I just updated my Kodi to 19.1 and currently there's no providers problem. But when I try to watch SW: Empire Strikes Back, both providers given aren't playable and I'm sure that my resolvesurl is updated to latest version (5.1.45)

**Comment by deeppzy** [comment]
What do you mean by "scene title" and scrape. I just started using Kodi a month ago but I don't know much about it.
