### ISSUE TITLE
Oathscrapers Issue in SPMC 16.7-01

### ISSUE THREAD

**Issue by Arfgul** [host505/plugin.video.theoath#36]
Hi,

There seems to be an issue when pulling links and playing links with real-debrid associated to ResolveURL.  The Oath: Resolving dialogue box will hang for about 5 min before it moves on to show the real-debrid links.  Then, it will take an extra 5 min to load the actual link. I have tried clearing providers cache, resetting cache function, clearing debrid checks and uninstalling/installing.  Please let me know if I could provide any more information.

**Comment by host505** [comment]
I guess you have resolveurl 5.1.43? As I believe that's the last compatible with spmc 16 version.
Probably the issue occurs upon communication between resolveurl and rd, but hard to tell without a log.

**Comment by Arfgul** [comment]
Each device is 
[kodi.log](https://github.com/host505/plugin.video.theoath/files/7772610/kodi.log)
using ResolveURL 5.1.54.  I have also re-created the issue in Kodi 17.6.  I have attached the log as requested.

**Comment by host505** [comment]
Forgot about this. Does this issue still exist?
Your log didn't say much, albeit it wasn't a debug log.
As I previously said I don't have that issue on my old device with spmc.

**Comment by Arfgul** [comment]
No worries.  I found out it has to do with the ISP blocking real-debrid.  Seems like the only fix is to replace modem.
