### ISSUE TITLE
Many duplicates torrents in source results

### ISSUE THREAD

**Issue by 123Venom** [host505/plugin.video.theoath#37]
Hashes are usually seen lower and upper case from torrent site to site so one needs to comp the same case HASHES or you get duplicates.

your `uniqueSourcesGen()` method needs a case check to comp because you are returning many duplicates.

```url = url[:60].lower()```

First 60 nicely returns after the hash but if the case from one site to the next differs your match check fails and you get duplicates, and a lot of them.  Then some site returns base32 while others return hex40.  AD and PM convert those for you ...but RD sucks ass and you need to manually convert those.

**Comment by host505** [comment]
Noted for next update, thx
