### ISSUE TITLE
Show most popular posters

### ISSUE THREAD

**Issue by htatla81** [host505/plugin.video.theoath#38]
Hi host505

im moving to using the oath from ExodusVPN and I note the on many occasions the artwork showing for TV shows (for Main entry & seasons) isn’t the “main” artwork you would expect or the ones that are highest rated/voted on TVDB site

can I ask whether oath picks the most voted artwork or how the app picks the ones to display?

i have a TVDB API key but using this didn’t seem to make much difference 

PS: loving the app and your work

**Comment by host505** [comment]
Theoath doesn't use tvdb anymore, no idea where you saw that tvdb api setting. You'd probably be better suited to keep using that exodusvpn (lol) copycat.

**Comment by htatla81** [comment]
Sorry I meant TMDB API which is on Accounts section in settings - does it grab the most voted artwork or what’s the criteria?

Lol copycat is old news.. I’m using the best now :)

it was an old firestick that I hadn’t updated since before covid

**Comment by jewbmx** [comment]
Think the artwork is just first available item that matches the users language setting. Or atleast thats how mine works. (Although mines English Only now lol.)

**Comment by htatla81** [comment]
Yeh think that’s correct after checking on TMDB and comparing. 

Shame you can’t vote on the best poster to take #1 spot, on this basis. Some choices are pretty whacky and not “official” looking or have odd crops

**Comment by htatla81** [comment]
@host505 so does Oath pick 1st on the list or highest voted artworks?

**Comment by host505** [comment]
It uses the only one available from the main tv/movie api call. It doesn't use the `images` api endpoint that has a list of images to pick from. It used to, but I changed that, as it acquired more data from the api.
It won't change back.

**Comment by belltell** [comment]
Hi host505

Can you please add under The Oath Settings in Sources Filters an option just 'Remove Uncached' ?

I see there is a 'Remove uncached torrents if cached exist'. It'll be great to have an option to just 'Remove Uncached' period. TIA
