### ISSUE TITLE
The Oath won't install anymore

### ISSUE THREAD

**Issue by keem85** [host505/plugin.video.theoath#39]
Hi there

I installed Matrix 19.3 yesterday, a complete wipe, and not it seems The Oath won't install.. I get that resolved module won't be satisfied, or something in the lines of that. It's strange because I have the newest Kodi version from Android Play Store on my nVidia Shield TV.
Could you see if there are any issues with your dependencies? Or if there is something else causing this?

Log: https://paste.kodi.tv/imumetuxut

**Comment by host505** [comment]
No I haven't changed anything on my repo structure for over a year at least.
It's probably one more side effect of the new shield update (well Android 11 actually) - something about permissions. 
The problem seems to be the installation of resolveurl, can you try installing SMR link tester add-on through my repo?

**Comment by keem85** [comment]
Hmm I get the same resolvedURL won't be satisfied error on the SMR Link tester aswell.
To try and fix the Android 11 issue I did copy out the whole .kodi data folder via X-plore on to my PC, I then inherited write permission to all the kodi folders and subfolders before putting it back to my Shield. So permissions inside android/data/kodi shouldn't be an issue anymore, I think.. Also, other applications like Fen and Seren installs just fine, I think there is something with that resolvedURL dependency that fails.

**Comment by keem85** [comment]
Yeah I think you're right, it's an Android 11 issue, I regret I updated to it.
Same error with installing the package from alternative link. I could install the .zip, but not install from resolveurl repository.. Maybe resolveurl uses some system folders that are not accessed anymore..

**Comment by host505** [comment]
Can you install from zip the latest resolveurl package?
https://github.com/Gujal00/smrzips/blob/master/zips/script.module.resolveurl/script.module.resolveurl-5.1.59.zip
This will determine if the problem exists on resolveurl repo or resolveurl itself.

**Comment by keem85** [comment]
Yep I managed to install via that link! But upon installing The Oath now I get the same error, but with "script.artwork.theoath version 0.0.0 could not be satisfied" instead. Very strange

**Comment by keem85** [comment]
I will try to install the dependencies manually, one by one

**Comment by host505** [comment]
If it proves to be an Android 11 issue and not specialised to the Shield, I'll revisit it. Colsing fornow.
