### ISSUE TITLE
Have an option to Filter out All Uncached Torrents from results 

### ISSUE THREAD

**Issue by belltell** [host505/plugin.video.theoath#40]
Hi host505

Can you please add under The Oath Settings in Sources Filters an option just 'Remove Uncached' ?

I see there is a 'Remove uncached torrents if cached exist'. It'll be great to have an option to just 'Remove Uncached' period.

 TIA (I'm using Matrix version)

**Comment by host505** [comment]
No, when there's no cached you're presented with the uncached so you can cache one yourself = more cached stuff for everyone.
I was intending to remove them anyway only when autoplay is on though.

**Comment by belltell** [comment]
Thanks for the speedy reply. On you next update if you can add the option and leave it disabled by default would be great.

Thanks for the great add-on!
