### ISSUE TITLE
Mark as watched 

### ISSUE THREAD

**Issue by htatla81** [host505/plugin.video.theoath#42]
Hi there

I’m having an issue with “mark as watched” which only seems to work automatically when you have watched to the very last second and your taken to main screen

what I would expect is it to still mark as watched if I have watched up to the credits roll and I press stop, so perhaps +90% of the way, but this doesn’t handle this currently 

As always appreciate all the efforts and loving your work!

**Comment by host505** [comment]
It should mark as watched when you've played 92% of the item's total time. It works for me, using Trakt indicators, but I extensively tested local indicators too, as I've rewritten that part.
Are you using Trakt or local indicators?

**Comment by htatla81** [comment]
I'm using Local indicators not Trakt currently. For example im watching Succession S02 E05, around

**Comment by host505** [comment]
Are you sure it's not? Did you back out on seasons menu and then back in to episodes and it isn't marked as watched?
Going back to episodes from the sources list won't have fresh watched status results (unless you activate "Refresh watched status" on Playback settings).

**Comment by htatla81** [comment]
Yes I’m sure and I’m pressing “stop” at credits. I will try tonight on Ep05 and report back. 

Again when watching to the natural end of a stream the ep list will refresh and mark as watched on its own (so perhaps I have refresh status on already) - FYI I’m on a firestick 

Perhaps you could drop down to 90% and I can test? I think it just needs a little more flex on the %watched
