### ISSUE TITLE
Download functionality not working

### ISSUE THREAD

**Issue by langdonr621** [host505/plugin.video.theoath#46]
hi there,

after upgrading to 4.11.02, the Download functionality (from the context menu) stopped working.  to reproduce:

1. bring up the streams for either s movie or a TV episode.
2. make sure you target a working stream by first playing it.
3. click + hold (i use an android top box w/ remote controller) until the context menu appears,
4. select the Download option.
5. nothing happens when before a dialog appears stating the file size and whether or not to continue w/ the process.

**Comment by host505** [comment]
Right, found the problem.

**Comment by langdonr621** [comment]
brilliant!  thanks for your prompt response + the work you provide.

**Comment by host505** [comment]
fixed in ed96d69e2a722a5ffa2137c226042951ad21cab5
