### ISSUE TITLE
About new rlsbb domain

### ISSUE THREAD

**Issue by marson53** [host505/plugin.video.theoath#47]
Hi could you help, in the UK the rlsbb site got blocked 2 days ago, they have given us new link now to access the site, I put the new link Custom Domain but it it won't work, could you help, Thanks new link      http://bbrls.in/

**Comment by marson53** [comment]
Yes , I put the new site in custom domain, it doesn't matter what I search for, it doesn't find any links for me, I also changed the scraper in fenom scrapers, which is the same no links ,  the link seems good I can access the site and search, but it won't work when changing to it ,don't know why this one won't work for me , it should work

**Comment by host505** [comment]
Is what you're searching for released in 2021 or after? They moved their old posts last year to other domains starting with old3.
Sometimes these don't work, and the custom domain doesn't apply for releases older than 2021. It sucks actually.
Search for eg w4lking d3ad 11x09, does it work? It does for me.

**Comment by marson53** [comment]
Thanks for replying to help me, you can delete this now , for some reason it's just started working , don't know what happened, sorry to waste your time

**Comment by host505** [comment]
Np
