### ISSUE TITLE
super_info/worker bogus log error

### ISSUE THREAD

**Issue by 123Venom** [host505/plugin.video.theoath#48]
Every page that loads for tvshows/movies throws a bogus log error, or at least I call it that when it causes no real problems.

<img width="1003" alt="index issue" src="https://user-images.githubusercontent.com/46383815/158007146-acc0c32f-3f52-4b1e-9156-5d2af37244a8.PNG">

Reason it happens is in the `worker()` method.  If you notice the `total = len(self.list)` may return 20 but the index is actually 0-19 so where you say `if i <= total:` it will never be equal so it's actually trying to make one additional call to `super_info()` for index 20 that does not exist and hence throws the index error.  Remove the `=` sign in all cases and this bogus log error will go away.

**Comment by 123Venom** [comment]
Also noticed a problem in your `if self.meta: metacache.insert(self.meta)`..look close at your dent.  That insert method handles all meta items and you dented it inside the loop so you are effectively making that call 20 times.  It only need be called once to write all of `self.meta` items to db.

**Comment by host505** [comment]
And I've been wondering what this error was lol
Haven't really touched this piece of code, it's been like that since exodus, but makes sense what you say.
Thanks.

**Comment by jewbmx** [comment]
Im happy for both those fixes lol, the log error is obnoxious as hell and that self.meta change improves the loading speed quite nicely. Never noticed either before

**Comment by 123Venom** [comment]
You're right...I forgot that's an age old exo gaff.  I just checked The Crew..both the index and dent error exists there as well, they prob all got it.  Could actual say `total=len(self.list)-1` and leave the `=` I suppose.  I think the reason it's sneaked by so long is exo's lack of logging errors so you don't see it till you start logging those exceptions. `except: pass` and they're not seeing it and a big reason I've ventured away from that.

It's bit me before even on fresh code using `total=len()` and then `range(0,total)` not realizing that's going to have an extra index vs. the total count.

**Comment by jewbmx** [comment]
If i read a site earlier properly the error stands out more in python 3 because some changes somewhere and it wasn't much of a problem in 2. But i could be off on the info since i was just skimming quickly while scrolling lol

**Comment by 123Venom** [comment]
Unless you have error capturing in that exception you're just not seeing it.  The index issue should be the same for py2 or 3.  You could replace
```
pass
```

with 

```
import traceback
traceback.print_exc()
```

**Comment by host505** [comment]
Those changes have been applied on the recent version.
Thanks again

**Comment by 123Venom** [comment]
Side note:

Anyone notice yet that `execute('Action(Queue)')` no longer works in Matrix but does on Leia?  Take a show level and use your context menu option _**Queue Item**_ .  Then the pullout menu will now have **Current playlist** so you can view it.  Compare that same playlist between Leia and Matrix and you'll see it.  I've not gotten to the bottom of it yet if there's even anything we can do, besides building our own playlist which might be the only solution for Matrix.

**Comment by 123Venom** [comment]
2nd side note:

https://github.com/host505/plugin.video.theoath/issues/49
Nice bit of work there and I agree with what you did.  Being anal retentive I ended up then reviewing that entire class of more old exo code...and yikes!

```
langs = []
    try:
        try: langs = langDict[control.setting('subtitles.lang.1')].split(',')
        except: langs.append(langDict[control.setting('subtitles.lang.1')])
    except: pass
    try:
        try: langs = langs + langDict[control.setting('subtitles.lang.2')].split(',')
        except: langs.append(langDict[control.setting('subtitles.lang.2')])
    except: pass
 ```

 I did not get far and that whole block above is a ton of dog poo.  First `.split(',')` will NOT throw an exception if it fails to split it at a comma, if it exists or not.  The only thing to be concerned with there is "Does our settings match the items/order in our langDict?".  They do.  Then question, "will the setting ever return a null"...nope because we set a default so even if user does not change anything the default is returned and found in the langDict.
 
```
langs = langDict[control.setting('subtitles.lang.1')].split(',')
langs = langs + langDict[control.setting('subtitles.lang.2')].split(',')
```
Above does the same thing and 6 titles I tested still no problem.  We do not even need `langs=[]` there

Then I noted we raise an Exception if the default subs stream matches our primary sub lang ONLY..but why only that stream if there a bunch more in the torrent?  Take one tested and checked of the movie **Dune**

```
magnet:?xt=urn:btih:d7b21ca3a5556b8012a65b37b9484f2e0c0bdda5&dn=Dune.2021.2160p.BluRay.REMUX.HEVC.DTS-HD.MA.TrueHD.7.1.Atmos-FGT
```

`subLangs = xbmc.Player().getAvailableSubtitleStreams()`

returned this for available subs in the cached stream....

```
subLangs=['eng', 'eng', 'eng', 'fre', 'ger', 'ita', 'spa', 'chi', 'chi', 'kor', 'spa', 'dan', 'fin', 'gre', 'nor', 'swe', 'fre', 'ger', 'ita', 'spa', 'spa', 'hin']
```

That's quite the shit ton of subs in that torrent so I then played with int values like `return xbmc.Player().setSubtitleStream(5)` and I got the matching index for the ita/Italian sub, man just saying that makes me hungry..lol.  Anyway we can move freely thru the subs index.  So I questioned why are we only returning `.getSubtitles()`,  that returns the default,  vs. checking if there's a matching sub in the stream?

Number of tweaks that can be done to that class.
Yes I'm anal and believe in smaller footprint the faster the code executes, all wet or not..lol

**Comment by host505** [comment]
Yep, that's exactly what I did in that block:
https://github.com/host505/plugin.video.theoath/blob/master/resources/lib/modules/player.py#L376-L391

**Comment by 123Venom** [comment]
Ya I saw that block but just now realized I gaffed my own reading of what you did there.  I choked on line 374 but that's only going to raise the Exception if the default sub stream matches the primary lang, if not then your new block of code runs.  Nicely done to check other sub streams available in the source!!

That renaming to fix the `gre` issue, is that also why you used `xbmc.convertLanguage(sub_lang, xbmc.ISO_639_2)`?  I assumed so but when I logged `.getSubtitles()` and `.getAvailableSubtitleStreams()` they seemed to already return ISO_639_2....no? Kodi docs just claimed returns sub stream name/names...lol..made me wonder wtf would it be so logged it.

I was shocked to see how many sub streams were in a number of source links for **Dune** without any indication in link title that subs were included.

**Comment by host505** [comment]
Maybe it was a redundancy to use `xbmc.convertLanguage` there, but I'm not sure if kodi does this for the subs streams internally already or if it just displays the stream's subs tag, in which case it depends on the rip.
I was hopping that it would handle the 'gre'/'ell' thing but it didn't.
Aaaand I was wrong about 'gre' being a country code lol, it's also a valid lang code along with 'ell'.
Yet, kodi with `xbmc.convertLanguage(sub_lang, xbmc.ISO_639_2)` still returns 'gre', but in order to force the subtitle to the player it expects it to be 'ell'... Go figure

**Comment by 123Venom** [comment]
agreed.

btw..you catch the thing I mentioned further up in regards to `execute('Action(Queue)')` in Matrix?

**Comment by host505** [comment]
Yea I saw it. Never noticed as I hardly ever used the feature lol
I'll have a look, if it's kodi v18/19 or py2/3 related

**Comment by 123Venom** [comment]
I don't use the feature either and since I no longer support Leia I removed the context menu option to add to playlist since it appears fucked in Matrix.

**Comment by jewbmx** [comment]
Lol i was thinking about this queue issue the other day and was gonna ask if anyone knows what its even for lmao, ive never clicked it unless it was an accident. Been wanting to ditch it lol

**Comment by 123Venom** [comment]
I've messed with it in Leia.  If you Queue up a show item it would add all seasons/episodes to the Kodi playlist.  You'd then use the pullout to `View current playlist`.  Then you'd just use `Play from here` and the entire damn show would play.  Was cool till you realize you fall asleep to wake next morning with way more shit played than desired.  I added a NextFlix style popup xml now in case you fall asleep it can be set to go into pause mod.  The Queue is totally fucked in Matrix...you get a broken single url now.  I even did a side by side since I have a portable setup so I can cross check Leia shit, even though I put it to pasture, and Leia still works fine.

**Comment by host505** [comment]
Past couple of days I've been doing the same thing I did for subs for audio too `getAvailableAudioStreams`/`setAudioStream`.
Thought maybe `xbmc.convertLanguage` on audio streams might had better lack setting the desired audio when audio labels/tags are poorly labeled vs the kodi setting, but nope, still the same. So I'll pass on it and still rely on the kodi setting.

**Comment by 123Venom** [comment]
Found something else you might be interested in.  I spotted a **note to self** condition in your sources module that reminded me of the issue when I fought with it.

```
if pre_emp == 'true': # don't know why pre-emp needs 2nd pass filtering/sorting, but it does
    self.sourcesFilter(sort=True)
```
What is happening when pre_emp terminates a thread instance or two may still be running.  Then you filter away and all of a sudden you spot these straggler sources that did not get filtered out and wonder where the hell they came from.  Once the thread completes it adds to `self.sources` but your filtering might be half done so they sneak in.  What I did was all my threads return `self.scraper_sources` but after we exit the loop I use `self.sources.extend(self.scraper_sources)`.  Now if any threads complete it'll add to `self.scraper_sources` and no longer be an issue because It can no longer modify the contents of `self.sources`.  You'd have to modify your `getMovieSource()` and `getEpisodeSource()` methods but it'd then allow you to remove that extra filtering.

**Comment by 123Venom** [comment]
`del threads` it's good you have that and it'll stop any other remaining threads from starting but it doesn't kill any that are running and that's the issue.

**Comment by host505** [comment]
I think I came to the same conclusion at some point and was trying to find a way to kill the already running threads, but turned out it was more complex than I thought would be, and potentially result in many more problems, so I gave up.
Never would've thought of that approach to redirect those unfinished threads/sources. 
It also happens on manual pre-termination, ie too-early canceling of progress dialogue.

**Comment by 123Venom** [comment]
You're exactly right.  It's basically any early termination that has the issue.  I think once I added a `terminate on cloud sources` the issue got worse for me and had to come up with a solution.  Another idea would be your own little `.is_alive()` loop to sleep till it finishes.  I doubt it add more than a few 10ths of a second waiting for a running thread to finish.  Plus it'd allow you to keep those sources and not muck up your filtering being added later and still allow you to remove that extra filtering step.  I was recently doing some profiling and fooled with such a test case.

<img width="664" alt="threads" src="https://user-images.githubusercontent.com/46383815/161600772-9bf31188-e3fb-43f4-b71b-f5f86785ba44.PNG">


I was just trying to catch the timestamp between the running threads when it'd log.
