### ISSUE TITLE
Converting to UTF-8 if source is not UTF-8

### ISSUE THREAD

**Issue by ameer4** [host505/plugin.video.theoath#49]
I want to enable converting to UTF-8 feature all the time because many of old subtitles in my language (Arabic) encoding at ANSI, but newer version ones already encoded at UTF-8.

Problem: when enabling the converting it always convert even utf-8 which completely broke UTF-8 subtitles showing rubbish characters.
It is very annoying to disabling/enabling it every time depending on the video files!

We need this feature to convert only if the file is not already on UTF-8, otherwise leave UTF-8 subtitles untouched.

**Comment by ameer4** [comment]
I'm not sure how it broke UTF-8 subtitles files, since when converting it to same encoding it is supposed to be already intact, yet if the source is utf-8 it broke it somehow!

**Comment by host505** [comment]
Yea I can check what the api reports about encoding, and if it's utf-8 already skip the convertion.

**Comment by host505** [comment]
Ok can you check if it still happens with the new version out?

**Comment by ameer4** [comment]
> Ok can you check if it still happens with the new version out?

Yes it worked correctly now!
Thank you very much!
Now I can leave that setting enabled forever.

The only additional features regarding subtitles I would like to see:
1- Adding another subtitles providers especially subscene.com.
2- Ability to choose other subtitles from same searching results, by -say- long clicking on a video and clicking subtitles it then give me a list to choose depending on language selected in settings.
 (Because sometimes especially with old video the choosing subtitles usually not in sync)

**Comment by host505** [comment]
Subscene doesn't have a public api I could use afaik, but regardless, it's too much work I'm not interested in doing right now.
I could easily add a subtitles choosing option which would be activated through settings (ie you set either auto dl or select dialogue) but I don't see the point when there are pretty decent subs add-ons out there.

**Comment by ameer4** [comment]
Yeah that's makes sense, but other tool don't convert!!
I already sent a message to the developer of a4ksubtitles regarding conversion feature, since your tool is the only tool I know that convert on the fly.

Thank you for your efforts.
