### ISSUE TITLE
Can you add this site as well?

### ISSUE THREAD

**Issue by lavara123** [host505/plugin.video.theoath#51]
A site with good content

https://swatchseries.ru

**Comment by host505** [comment]
This site really doesn't like to be scraped. You need to go sideways to even get the search url.
Can't add it sorry.
Ps this is not the original swatchseries (for which I had a scraper but the site went down afaik), it's a copycat.

**Comment by jewbmx** [comment]
I could make you about 30 or more scrapers like that site if anyone can show me how to get the final links on the item page lol. Thats a very popular "site template"

**Comment by host505** [comment]
@jewbmx which scraper of those you gave me fits that site? I don't think it's anyone, did you try to use their search?

**Comment by jewbmx** [comment]
Ive made many that use that exact site template but never got the final links figured out so i just deleted them all and added most the sites to a special section in my url lists. I havent seen anyone else figure the code out so its pretty much trash sites unless your on a browser in my opinion.
