### ISSUE TITLE
Autoplay episodes

### ISSUE THREAD

**Issue by djdirty60** [host505/plugin.video.theoath#53]
Good day,

Is it possible that there will be a function that automatically plays the episodes and that you can still choose from the movie on the left?

thanks in advance

**Comment by host505** [comment]
> from the movie on the left

I don't know what that means, but, apart from kodi's built-in "Play from here" (which currently has it's [problems](https://github.com/host505/plugin.video.theoath/issues/41)) there's no other means to auto-play next episodes, neither plans for it, sorry

**Comment by 123Venom** [comment]
lol..did not make a lick of sense to me either..."movie on left"?  What the side pull out?  People think these one liner questions and we have a clue what they mean.  Pic and details means soooooo much but few get it.

Reminds me of my 85 year old mother.."can you get me that thing", "what thing mom?", "you know that thing on the thing next to the thing?"

Who's seen the commercial with Dave Grohl and Kevin Hart, "I made Lasagna"?  I coin it, new dev phrase..lol
