### ISSUE TITLE
My TV Shows (Trakt) > Collection: Error 500

### ISSUE THREAD

**Issue by Material-Scientist** [host505/plugin.video.theoath#54]
Hi,

For about a week or so, using Trakt's "My TV Shows > Collection" link has been resulting in error 500.
Happens on my desktop (Win10) and on my Raspberry.

![image](https://user-images.githubusercontent.com/40465719/160187574-f9834052-547e-4cdf-a5ad-03a05ad3a7eb.png)

I tried reinstalling the addon and re-authorizing Trakt. 

System 1:
Windows 10
Kodi 19.3
TheOath 4.11.07

System 2:
LibreElec 9.2.8
Kodi 18.9
TheOath 4.10.1

**Comment by host505** [comment]
This indicates a trakt server error.
How many items do you have in your tv shows collection? Are you able to access it through other add-ons/apps?
I can access it just fine, but I only have 104 items.

**Comment by TapMeDead** [comment]
> Hi,
> 
> For about a week or so, using Trakt's "My TV Shows > Collection" link has been resulting in error 500. Happens on my desktop (Win10) and on my Raspberry.
> 
> ![image](https://user-images.githubusercontent.com/40465719/160187574-f9834052-547e-4cdf-a5ad-03a05ad3a7eb.png)
> 
> I tried reinstalling the addon and re-authorizing Trakt.
> 
> System 1: Windows 10 Kodi 19.3 TheOath 4.11.07
> 
> System 2: LibreElec 9.2.8 Kodi 18.9 TheOath 4.10.1

Could you reproduce the error and post your log? I am sure the error there will help us figure this out.

**Comment by Material-Scientist** [comment]
It appears removing some shows does fix the problem, thx!

**Comment by host505** [comment]
Thx too for answering my questions. Oh wait.
What a waste has this become.
