### ISSUE TITLE
Multi-genre selection

### ISSUE THREAD

**Issue by jjred1977** [host505/plugin.video.theoath#6]
I was pretty sure that The Oath had the ability to choose multiple genres (ex. horror/sci-fi) when searching for content to watch.  Was this ability taken away or moved in the add-on? It's a feature I used a few times and since an update I haven't been able to find it.  It might have been in Scrubs2 so if I have the wrong add on my apologies.

**Comment by host505** [comment]
If you're talking about the Genres category, no I've never touched that part.
