### ISSUE TITLE
Clean Settings wipes all setting in Kodi 17 and under.

### ISSUE THREAD

**Issue by Tikipeter** [host505/plugin.video.theoath#9]
Hi host505.

I realized while browsing the net, that Venom also uses this code, and runs it for each new addon update. This revealed an incompatibility with Kodi 17 that I never even thought about (Kodi 17 doesn't come into my mind anymore).

Anyway, I've re-written the code to include compatibility with Kodi 17 or under and Kodi 18 and over.

https://pastebin.com/1VQSRuVv

There's a format error that appeared near the top of that pastebin, plus you'll need to paste in your own "get_kodi_version()" function.

All the Best. :)

**Comment by host505** [comment]
Hi Tikipeter,
Thanks for letting me know about this and even providing me with your fix, that's so kind of you :)
I still encounter one small problem under kodi 17: for "action" type settings, a `value` of "None" is set.
Doesn't seem to be causing any problems, it's just aesthetic.
I tried some stuff but I can't get rid of it, maybe you have some idea?
Thanks again

**Comment by Tikipeter** [comment]
Ah, I never noticed that. Leave it with me and I'll see if I can work it out..

**Comment by host505** [comment]
I think I figured something: in your paste, line 21, I changed it from:
`else: content += '\n    <setting id="%s" value="%s" />' % (item['id'], default_settings[active_ids.index(item['id'])])`
to:
`else: content += '\n    <setting id="%s" value="" />' % item['id']`

Not sure of the use of that element you used there actually, maybe I shouldn't remove it?

**Comment by Tikipeter** [comment]
That code, I just realized, was not needed. I was grabbing the default values for the settings, so the defaults were put into the new settings file when nothing else was there. But, now I realize that isn't needed.

When I was testing the code, I didn't have it right at first, and it made a slightly wrong new settings.xml. Then when I went to fix it, I was using that wrong xml as the base for fixing it. It made it look like I needed to fill in the 'default' setting values when no user value was set.

You're right, none of that is needed at all. Also, some other things aren't needed.

Here's an updated correct version with everything unnecessary removed:
https://pastebin.com/Xm1PRJKV

Thanks for pointing that out for me. :)

**Comment by host505** [comment]
Thanks, everything seems to be working now on both 17 & 18.
Just for this to be complete for anyone reading and finds it useful, you forgot to add the 
```
            nfo_file = xbmcvfs.File(settings_xml, 'w')
            nfo_file.write(new_content)
            nfo_file.close()
```
part on your 2nd paste, under line 51.
Thanks again for that great piece of code, Tikipeter, and for being so kind to let me aware of the issue :)
I'll update my add-on with it right now.

**Comment by Tikipeter** [comment]
Ha! Of course I did! Thanks host505. :) :)
